config/routes.rb
Docs::Application.routes.draw do
  mount RailsAdmin::Engine => '/app_admin', :as => 'rails_admin'
  devise_for :users
  comfy_route :cms_admin, path: '/site_admin'

  authenticated do
    root to: 'home#loggedin', as: :autenticated_root
  end

  root to: 'comfy/cms/content#show'


  resources :revises do
    member do
      get :fix
      get :unfix
      get :download
    end
  end

  get 'invoices', to: 'documents#invoices'
  get 'delivers', to: 'documents#delivers'

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end

  resources :nomenclatures do
    get :archived, on: :collection
  end
  resources :distributors, except: :show
  resources :documents, only: [:show, :edit, :update, :destroy] do
    member do
      get :download
    end
  end
  resources :orders do
    resources :documents, only: [:new, :create]
    member do
      get :accept
      get :pay
      get :ship
      get :unaccept
      get :unpay
      get :unship
    end
  end

  resources :messages do
    member do
      get :reply
      get :download
      get :sdestroy
    end
  end
  get 'outbox', to: 'messages#outbox'
  get '/docs/get/:id' => 'orders#download'

  get '/prices/:id' => 'prices#show', defaults: { format: 'json' }

  # Make sure this routeset is defined last
  comfy_route :cms, path: '/', sitemap: false


end

app/models/message.rb
class Message < ActiveRecord::Base
  include Authority::Abilities
  self.authorizer_name = 'MessageAuthorizer'
  paginates_per 10
  belongs_to :user
  belongs_to :parent, class_name: 'Message', foreign_key: 'parent_id'
  has_many :recipients

  validate :recipients_set
  validates :user, presence: true

  scope :outbox_nodelete, -> { where(deleted: false) }

  accepts_nested_attributes_for :recipients,
                                allow_destroy: true,
                                reject_if: :all_blank

  mount_uploader :attachment, AttachmentUploader

  def parents
    @parents ||= Message.get_parents(self)
  end

  private

  def self.get_parents(message)
    @tree ||= []
    if message.parent.nil?
      return @tree
    else
      @tree << message.parent
      get_parents(message.parent)
    end
  end

  def recipients_set
    errors.add(:Recipient, 'Не выбран ни один получатель') if recipients.empty?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include EmailNotify
  before_action :authenticate_user!
  before_action :set_user, only: [:index, :outbox, :show]
  before_action :set_message, only: [:show, :download, :sdestroy, :destroy]
  authorize_actions_for Message
  authority_actions outbox: 'read', download: 'read', sdestroy: 'update'

  def index
    @title = 'Входящие сообщения'
    @box = 'inbox'
    @messages = current_user.messages.where(recipients: { deleted: false, user: User.current })
                .order('messages.created_at desc').page(params[:page])
    @new_messages = current_user.messages.where(recipients: { readed: false, deleted: false, user: User.current })
    render partial: 'messages/messages_table' if request.wiselinks_partial?
    session[:previous_path] = messages_path
  end

  def outbox
    @title = 'Исходящие сообщения'
    @box = 'outbox'
    @messages = Message.where(user: current_user).outbox_nodelete.includes(:recipients).order('created_at desc').page(params[:page])
    if request.wiselinks_partial?
      render partial: 'messages/messages_table'
    else
      render 'index'
    end
    session[:previous_path] = outbox_path
  end

  def new
    @title = 'Новое сообщение'
    @message = Message.new
    @logist = false
    if @user_roles.include?('logist')
      @logist = true
      users = User.with_any_role(:distributor, :logist)
      users.each do |u|
        @message.recipients.build(user: u)
      end
    else
      logist_users = User.with_role :logist
      logist_users.each do |u|
        @message.recipients.build(user: u)
      end
    end
  end

  def reply
    @title = 'Новое сообщение'
    @parent = Message.find(params[:id])
    authorize_action_for(@parent)
    @message = Message.new(parent_id: params[:id])
    @message.recipients.build(user: @parent.user)
  end

  def create
    @message = Message.new(message_params)

    respond_to do |format|
      if @message.save
        format.html { redirect_to messages_path, notice: 'Сообщение успешно отправлено' }
        format.json { render action: 'show', status: :created, location: @message }
        notice('new_message', message: @message)
      else
        format.html { render action: 'new' }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    authorize_action_for(@message)
    @title = 'Сообщение'
    rm = @message.recipients.where(user_id: current_user.id).first
    unless rm.nil?
      rm.readed = true
      rm.save!
    end
  end

  def download
    path = URI.decode(@message.attachment.url)
    send_file path, x_sendfile: false
  end

  def sdestroy
    if @message.user == current_user
      @message.deleted = true
      @message.save!
    else
      rm = @message.recipients.where(user_id: current_user.id).first
      rm.deleted = true
      rm.save!
    end
    redirect_to messages_path, notice: 'Сообщение удалено'
  end

  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private

  def set_user
    current_user = User.current
  end

  def set_message
    @message = Message.find(params[:id])
  end

  def message_params
    params.require(:message).permit(:subject, :body, :attachment, :user_id, :parent_id, recipients_attributes: [:user_id, :_destroy])
  end
end

app/views/messages/_form.html.slim
= simple_form_for(@message) do |f|
  == render partial: 'form_shared/errors', locals: {model_var: @message}

  .form-inputs
    .row
      .large-6.large-push-6.columns
        - if @logist
          fieldset
            legend Получатели
            dl.accordion(data-accordion)
              dd
                = link_to 'Дистрибьюторы', '#acc1'
                #acc1.content.active
                  = f.simple_fields_for :recipients do |r|
                    - if r.object.user.has_role?(:distributor)
                      = r.input :_destroy, as: :boolean, label: false do
                        = r.check_box :_destroy, {class: 'distributor'}, 'false', 'true'
                        - recipient_name = r.object.user.distributor.nil? ? 'не задан' : r.object.user.distributor.name if r.object.user.has_role?(:distributor)
                        = r.object.user.full_name + ' (' + recipient_name + ')'
                      = r.input :user_id, as: :hidden
                  = link_to 'Выбрать всех', '#', class: 'button secondary tiny check_all', id: 'check_distr', data: {checks: 'distributor', switch: 0}
              dd
                = link_to 'Логисты', '#acc2'
                #acc2.content
                  = f.simple_fields_for :recipients do |r|
                    - if r.object.user.has_role?(:logist)
                      = r.input :_destroy, as: :boolean, label: false do
                        = r.check_box :_destroy, {class: 'logist'}, 'false', 'true'
                        = r.object.user.full_name
                      = r.input :user_id, as: :hidden
                  = link_to 'Выбрать всех', '#', class: 'button secondary tiny check_all', id: 'check_logist', data: {checks: 'logist', switch: 0}

        - else
          = f.simple_fields_for :recipients do |r|
            = r.input :user_id, as: :hidden


      .large-6.large-pull-6.columns
        = f.input :subject, label: 'Тема:'
        = f.input :body, label: false
        = f.input :attachment, as: :file, label: 'Вложение'
        = f.association :user, as: :hidden, input_html: {value: @message.user_id.blank? ? User.current.id : @message.user_id}
        = f.input :parent_id, as: :hidden, input_html: {value: params[:parent_id]}

    .row
      .large-6.large-centered.columns
        = f.button :submit, 'Отправить'

app/views/messages/_messages_table.html.slim
.row
  .large-9.columns
    = paginate @messages, options: {data: {push: 'partial', target: '#messages'}}
    table
      thead
        tr
          th(colspan="2")
          th.text-center Тема
          th.text-center = @box == 'inbox' ? "Отправитель" : "Получатель"
          th.text-center Дата
          th
      tbody
      - @messages.each do |m|
        tr
          - if @box == 'inbox'
            td = link_to m.recipients.first.readed ? icon(:eye, :medium) : icon(:'burst-new', :medium), m, data: {replace: true, target: '#main'}
          - else
            td = link_to icon(:eye, :medium), m, data: {replace: true, target: '#main'}
          td = icon(:paperclip, :medium) unless m.attachment.blank?
          td = m.subject
          - if @box == 'inbox'
            td = m.user.full_name
          - else
            - users = User.find(m.recipients.collect(&:user_id))
            td = users.collect(&:full_name).join(', ')
          td = m.created_at.localtime.strftime('%d.%m.%Y %H:%M')
    = paginate @messages, options: {data: {push: 'partial', target: '#messages'}}

app/views/messages/_reply_form.html.slim
= simple_form_for(@message) do |f|
  .row
    .large-6.columns
      hr
      - if @user_roles.include?('logist')
        p = "Получатель: #{@parent.user.full_name} (#{@parent.user.distributor.try(:name)})"
      = f.input :subject, label: 'Тема:', input_html: {value: 'Re: ' + @parent.subject}
      = f.input :body, label: false, input_html: {placeholder: 'Текст сообщения'}
      = f.input :attachment, as: :file, label: false
      = f.association :user, as: :hidden, input_html: {value: @message.user_id.blank? ? User.current.id : @message.user_id}
      = f.simple_fields_for(:recipients) do |r|
        = r.input :user_id, as: :hidden
      hr
      = f.button :submit, 'Отправить'
    .large-6.columns
      = render partial: 'show_message', locals: {message: @parent}

app/views/messages/_show_message.html.slim
.panel
  h4 = message.subject
  p = sanitize message.body
  - unless message.attachment.blank?
    p = link_to "#{message.attachment.file.filename} (#{number_to_human_size(message.file_size)})", download_message_path(message)

app/views/messages/index.html.slim
- set_title(@title)
dl.sub-nav
  dt Сообщения:
  dd = active_link_to 'Входящие', messages_path, wrap_tag: :dd, data: {push: true, target: '#main'}
  dd = active_link_to 'Исходящие', outbox_path, wrap_tag: :dd, data: {push: true, target: '#main'}

= link_to 'Новое', new_message_path, class: 'button secondary tiny', data: {push: true, target: '#main'}

#messages
  == render partial: 'messages_table'

app/views/messages/new.html.slim
- set_title(@title)
.row
  .large-9.large-centered.columns
    h3 = @title

    == render 'form'

    = link_to 'Отмена', messages_path, class: 'button secondary small', data: {push: true, target: '#main'}

app/views/messages/reply.html.slim
- set_title(@title)
.row
  .large-9.large-centered.columns
    h3 = @title
    == render 'reply_form'


    = link_to 'Отмена', messages_path, class: 'button secondary small', data: {push: true, target: '#main'}

app/views/messages/show.html.slim
- set_title(@title)
.row
  .large-6.large-centered.columns
    == render partial: 'show_message', locals: {message: @message}


.row
  .large-6.large-centered.columns
    hr
    .large-6.columns
      = link_to 'Назад', session[:previous_path], class: 'button secondary tiny', data: {push: true, target: '#main'}
      - unless @message.user == User.current
        = link_to 'Ответить', reply_message_path(@message), class: 'button secondary tiny'
      = link_to 'Удалить', sdestroy_message_path(@message), class: 'button secondary tiny', data: {confirm: 'Удалить сообщение?'}
    .large-6.columns.text-right
      = link_to icon(:skull, :medium), @message, method: :delete, data: {confirm: 'Сообщение будет удалено безвозвратно'} if @message.user == current_user && @user_roles.include?('logist')