config/routes.rb
Docs::Application.routes.draw do
  mount RailsAdmin::Engine => '/app_admin', :as => 'rails_admin'
  devise_for :users
  comfy_route :cms_admin, path: '/site_admin'

  authenticated do
    root to: 'home#loggedin', as: :autenticated_root
  end

  root to: 'comfy/cms/content#show'


  resources :revises do
    member do
      get :fix
      get :unfix
      get :download
    end
  end

  get 'invoices', to: 'documents#invoices'
  get 'delivers', to: 'documents#delivers'

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end

  resources :nomenclatures do
    get :archived, on: :collection
  end
  resources :distributors, except: :show
  resources :documents, only: [:show, :edit, :update, :destroy] do
    member do
      get :download
    end
  end
  resources :orders do
    resources :documents, only: [:new, :create]
    member do
      get :accept
      get :pay
      get :ship
      get :unaccept
      get :unpay
      get :unship
    end
  end

  resources :messages do
    member do
      get :reply
      get :download
      get :sdestroy
    end
  end
  get 'outbox', to: 'messages#outbox'
  get '/docs/get/:id' => 'orders#download'

  get '/prices/:id' => 'prices#show', defaults: { format: 'json' }

  # Make sure this routeset is defined last
  comfy_route :cms, path: '/', sitemap: false


end

app/models/order.rb
class Order < ActiveRecord::Base
  acts_as_paranoid
  paginates_per 10

  include Authority::Abilities
  self.authorizer_name = 'OrderAuthorizer'

  has_paper_trail

  belongs_to :distributor
  belongs_to :user
  has_many :documents, dependent: :destroy, inverse_of: :order
  accepts_nested_attributes_for :documents,
                                allow_destroy: true,
                                reject_if: :all_blank

  has_many :order_items, dependent: :destroy, inverse_of: :order
  accepts_nested_attributes_for :order_items,
                                allow_destroy: true,
                                reject_if: :all_blank

  validates :distributor, :user, presence: true

  scope :current_distr, -> { where(distributor_id: Distributor.current) }

  ransacker :created_at, type: :date do |_parent|
    Arel::Nodes::SqlLiteral.new('DATE(orders.created_at)')
  end

  ### state_machine
  state_machine :state, initial: :pending do
    after_transition on: :accept do |order|
      order.send_email
    end
    event :accept do
      transition pending: :accepted
    end
    event :unaccept do
      transition accepted: :pending
    end
    event :pay do
      transition [:accepted, :shipped] => :paid
    end
    event :unpay do
      transition paid: :accepted
    end
    event :ship do
      transition [:paid, :accepted] => :shipped
    end
    event :unship do
      transition shipped: :accepted
    end
    state :pending
    state :accepted
    state :paid
    state :shipped
  end

  ############
  def user
    User.unscoped { super }
  end

  def total_summa
    order_items.to_a.sum(&:summa)
  end

  def total_nds
    order_items.to_a.sum(&:nds)
  end

  #### rails admin
  rails_admin do
    list do
      field :id do
        label '№'
      end
      field :distributor do
        label 'Дистрибьютор'
      end
      field :created_at do
        label 'Добавлен'
      end
      field :updated_at do
        label 'Изменен'
      end
      field :user do
        label 'Добавил'
        pretty_value do
          user = User.find(bindings[:object].user_id.to_s)
          user.full_name
        end
      end
    end
  end

  def send_email
    notify_users = User.with_role(:logist) - User.with_role(:logist_prime)
    notify_users.each do |u|
      UserMailer.new_order(u, self).deliver
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  include EmailNotify
  before_action :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy, :accept, :pay, :ship, :unaccept, :unpay, :unship]
  before_action :set_nomenclature, only: [:new, :update, :create]

  authorize_actions_for Order, except: :edit
  authorize_actions_for OrderItem, except: [:new, :accept, :unaccept, :pay, :unpay, :ship, :unship]
  authorize_actions_for Document, except: [:accept, :unaccept, :pay, :unpay, :ship, :unship]

  def index
    session[:previous_path] = orders_path
    @search = Order.includes(:distributor, :order_items).order('created_at desc').search(params[:q])
    if current_user.has_role? :distributor
      @orders = @search.result.current_distr.page(params[:page])
    else
      @orders = @search.result.page(params[:page])
    end
    render partial: 'orders/orders_table' if request.wiselinks_partial?
  end

  def show
    unless session[:previous_path] == delivers_path || session[:previous_path] == invoices_path
      session[:previous_path] = orders_path
    end
    @documents = @order.documents.order('created_at desc').page(params[:doc_page])
    @order_items = @order.order_items
    authorize_action_for(@order)
  end

  def new
    @order = Order.new
    @distr = params[:distributor_id]
    respond_to do |format|
      format.html
      format.js { render action: 'edit' }
    end
  end

  def edit
    @order_items = @order.order_items
    @nomenclatures = Nomenclature.mains.includes(:prices).where('prices.distributor_id' => @order.distributor.id, 'nomenclatures.archived' => false).page(params[:page])
    authorize_action_for(@order)
    authorize_action_for(@order_items)
  end

  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        notice('new_order', order: @order)
        format.html { redirect_to @order, notice: 'Заказ добавлен' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @order_items = @order.order_items
    authorize_action_for(@order)
    authorize_action_for(@order_items)

    begin
      respond_to do |format|
        if @order.update(order_params)
          session[:previous_path] = orders_path
          notice('update_order', order: @order)
          format.html { redirect_to @order, notice: 'Изменения успешно внесены.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @order.errors, status: :unprocessable_entity }
        end
      end
      rescue ActiveRecord::ReadOnlyRecord
        redirect_to @order, alert: 'Изменения позиций заказа заблокированы'

    end
  end

  def destroy
    authorize_action_for(@order)
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  def download
    document = Document.find(params[:id])
    authorize_action_for(document)
    path = URI.decode(document.file.url)
    send_file path, x_sendfile: false
  end

  authority_actions download: 'read'

  def accept
    authorize_action_for(@order)
    @order.accept
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Заказ согласовнан' }
      format.json { head :no_content }
    end
  end

  def unaccept
    authorize_action_for(@order)
    @order.unaccept
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Согласование заказа отменено' }
      format.json { head :no_content }
    end
  end

  def pay
    authorize_action_for(@order)
    @order.pay
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Оплата заказа подтверждена' }
      format.json { head :no_content }
    end
  end

  def unpay
    authorize_action_for(@order)
    @order.unpay
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Оплата заказа отменена' }
      format.json { head :no_content }
    end
  end

  def ship
    authorize_action_for(@order)
    @order.ship
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Заказ отгружен' }
      format.json { head :no_content }
    end
  end

  def unship
    authorize_action_for(@order)
    @order.unship
    respond_to do |format|
      format.html { redirect_to @order, notice: 'Отгрузка заказа отменена' }
      format.json { head :no_content }
    end
  end

  private

  def set_order
    @order = Order.find(params[:id])
  end

  def set_nomenclature
    if @distributor_id != 0
      @nomenclatures = Nomenclature.mains.includes(:prices).where('prices.distributor_id' => @distributor_id).page(params[:page])
    else
      if params[:distributor_id]
        @nomenclatures = Nomenclature.mains.includes(:prices).where('prices.distributor_id' => params[:distributor_id]).page(params[:page])
      end
    end
  end

  def order_params
    params.require(:order).permit(:user_id, :distributor_id, :memo, :docs,
                                  documents_attributes: [:id, :order_id, :file, :document_type_id, :user_id, :_destroy],
                                  order_items_attributes: [:id, :order_id, :nomenclature_id, :partner_number, :quantity, :price, :_destroy])
  end
end

app/views/orders/_filter.html.slim
= search_form_for @search, defaults: {required: false}, data: {push: 'partial', target: '#orders'} do |f|
  fieldset
    legend Фильтр
    .row
      .large-6.columns
        = f.text_field :id_eq, placeholder: 'Номер заказа', autocomplete: 'off'
      .large-6.columns
        .row.collapse
          .large-10.columns
            = f.input :created_at_date_equals, as: :datepicker, label: false, input_html: {placeholder: 'Дата заказа'}
          .large-2.columns
            span.postfix#clear-datepicker(data-no-turbolinks="true") X
    - if @user_roles.include?('logist')
      .row
        .large-12.columns
          = f.input :distributor_id_eq, as: :select, collection: Distributor.all, label: 'Дистрибьютор'
    .row
      .large-6.columns
        - states = {}; Order.state_machine.states.map() { |s| states[s.human_name] = s.name }
        = f.input :state_eq, as: :select, collection: states, label: 'Статус'
      .large-6.columns
        = f.input :docs_eq, as: :select, label: 'Док-ты'
    .row
      .large-12.columns


    = f.submit "Найти", class: 'button secondary tiny'
    = link_to 'Очистить', orders_path, class: 'button secondary tiny', data: {push: true, target: '#main'}

app/views/orders/_form.html.slim
= simple_nested_form_for @order do |f|
  = f.error_notification
  - new_order = current_page?(action: 'new')
  .row
    .small-8.column
      fieldset
        legend Позиции заказа
        - create_items = current_user.can_create?(OrderItem, for: @order)
        table#items
          tr
            th
            th
            th Партнерский номер
            th Цена
            th Кол-во
            th Сумма
            th НДС
            th
          = f.simple_fields_for :order_items, wrapper: false do |oi|
            tr.fields
              td = link_to icon(:book, :medium), '#', class: 'open-search-nomenclature', data: {no_turbolink: true} \
                if create_items
              td = oi.association :nomenclature, as: :hidden
              td(width="230") = oi.input :partner_number, label: false
              td = oi.input :price, as: :string, label: false, input_html: {readonly: true, class: 'text-right', step: 0}
              td.quantity-fields = oi.input :quantity, label: false, input_html: {class: 'text-center'}
              td = oi.input :summa, label: false, input_html: {class: 'text-right', readonly: true}
              td(width="80") = oi.input :nds, label: false, input_html: {class: 'text-right', readonly: true}
              td = oi.link_to_remove icon(:trash, :medium), title: 'Удалить' if create_items
        .row
          .small-6.columns
            p = f.link_to_add icon(:plus, :medium), :order_items, data: {target: '#items'}, title: 'Добавить позицию' \
              if create_items && !@nomenclatures.nil?
            input#ids(type="hidden")
        - if create_items
          .reveal-modal#nomenclature(data-reveal)
            == render 'nomenclature_search'
      .row
        .large-4.large-centered.columns
          .actions
            = f.button :submit, 'Сохранить'
      .row
        .large-4.large-centered.columns
          ul.button-group
            li
              = link_to 'Показать', @order, class: 'button secondary small', data: {push: true, target: '#main'}
            li
              = link_to 'Назад', orders_path, class: 'button secondary small', data: {push: true, target: '#main'}

    .small-4.columns
      fieldset
        legend Параметры заказа
        p == "Статус: <span class=\"#{@order.state_name} button tiny\">#{@order.human_state_name}</span>"
        = f.input :memo, label: 'Комментарий', input_html: {rows: 3}
        = f.input(:docs, as: :boolean, label: 'Документы получены') if @order.docsable_by?(current_user)
        = f.association :user, as: :hidden, input_html: {value: @order.user_id.blank? ? User.current.id : @order.user_id}
        = f.association :distributor, as: :hidden, input_html: {value: @order.distributor_id.blank? ? @distributor_id : @order.distributor_id}
  

app/views/orders/_form_logist.html.slim
= simple_nested_form_for @order do |f|
  = f.error_notification
  - new_order = current_page?(action: 'new')
  - create_items = current_user.can_create?(OrderItem, :for => @order)
  .row
    .small-8.column
      fieldset
        legend Позиции заказа
        table#items
          tr
            th
            th
            th Партнерский номер
            th Цена
            th Кол-во
            th Сумма
            th НДС
            th
          = f.simple_fields_for :order_items, wrapper: false do |oi|
            tr.fields
              td = link_to icon(:book, :medium), '#', class: 'open-search-nomenclature', data: {no_turbolink: true} \
								 if create_items
              td = oi.association :nomenclature, as: :hidden
              td(width="230") = oi.input :partner_number, label: false
              td = oi.input :price, as: :string, label: false, input_html: {readonly: true, class: 'text-right'}
              td.quantity-fields = oi.input :quantity, label: false, input_html: {class: 'text-center'}
              td = oi.input :summa, label: false, input_html: {class: 'text-right', readonly: true}
              td(width="80") = oi.input :nds, label: false, input_html: {class: 'text-right', readonly: true}
              td = oi.link_to_remove icon(:trash, :medium), title: 'Удалить' if create_items
        .row
          .small-6.columns
            p = f.link_to_add icon(:plus, :medium), :order_items, data: {target: '#items'}, title: 'Добавить позицию' \
							 if create_items && !@nomenclatures.nil?
            input#ids(type="hidden")
        - if create_items
          .reveal-modal#nomenclature(data-reveal)
            == render 'nomenclature_search'
      .row
        .large-4.large-centered.columns
          .actions
            = f.button :submit, 'Сохранить' unless params[:distributor_id].blank? && @order.distributor.nil?
      .row
        .large-4.large-centered.columns
          ul.button-group
            li
              = link_to 'Показать', @order, class: 'button secondary small', data: {push: true, target: '#main'}
            li
              = link_to 'Назад', orders_path, class: 'button secondary small', data: {push: true, target: '#main'}

    .small-4.columns
      - unless new_order
        .panel
          - if @order.state == 'pending' && !@order.id.nil?
            = link_to 'Согласовать', accept_order_path(@order), data: {:confirm => 'Согласовать заказ?'}, class: 'button tiny'
          - if @order.state == 'accepted'
            ul.button-group
              li = link_to 'Заказ отгружен', ship_order_path(@order), data: {confirm: 'Заказ отгружен?'}, class: 'button tiny'
              li = link_to 'Заказ оплачен', pay_order_path(@order), data: {confirm: 'Заказ оплачен?'}, class: 'button tiny'
              li = link_to 'Отменить согласование', unaccept_order_path(@order), \
								 data: {confirm: 'Отменить согласование?'}, class: 'button tiny secondary'
          - if @order.state == 'paid'
            ul.button-group
              /li = link_to 'Заказ отгружен', ship_order_path(@order), data: {confirm: 'Заказ отгружен?'}, class: 'button tiny'
              li = link_to 'Отменить оплату', unpay_order_path(@order), data: {confirm: 'Убрать отметку об оплате?'}, \
								 class: 'button tiny secondary'
          - if @order.state == 'shipped'
            ul.button-group
              li = link_to 'Заказ оплачен', pay_order_path(@order), data: {confirm: 'Заказ оплачен?'}, class: 'button tiny'
              li = link_to 'Отменить отгрузку', unship_order_path(@order), data: {confirm: 'Отменить отгрузку?'}, class: 'button tiny secondary'
      fieldset
        legend Параметры заказа
        - if new_order
          -if @distr.blank?
            = f.association :distributor, label: 'Дистрибьютор', required: true
          - else
            = f.association :distributor, as: :hidden, input_html: {value: @distr}
        p
          = "Дистрибьютор: #{@order.distributor.name}" unless new_order
          = @distr.blank? ? '' : "Дистрибьютор: #{Distributor.find(@distr).name}" if new_order

        p == "Статус: <span class=\"#{@order.state_name} button tiny\">#{@order.human_state_name}</span>"
        /- if @order.pending?
        = f.input :memo, label: 'Комментарий', input_html: {rows: 3}
        /- else
					= "Комментарий: #{@order.memo}"
        = f.association :user, as: :hidden, input_html: {value: @order.user_id.blank? ? User.current.id : @order.user_id}
        - if @distributor_id != 0
          = f.association :distributor, as: :hidden, input_html: {value: @order.distributor_id.blank? ? @distributor_id : @order.distributor_id}
        - else
          = f.association :distributor, as: :hidden, input_html: {value: @order.distributor_id.blank? ? @distr : @order.distributor.id}
            /fieldset
				legend Документы
				table#documents
					tr
						th 
						th Тип
						th Файл
					= f.simple_fields_for :documents, wrapper: false do |ff|
						tr.fields
							- if ff.object.new_record?
								td = ff.link_to_remove icon(:trash, :medium), title: 'Удалить'
								td = ff.association :document_type, label: false
								td = ff.input :file, as: :file, label: false
								td = ff.association :user, as: :hidden, input_html: { value: User.current.id }
							- else
								td = ff.link_to_remove icon(:trash, :medium), title: 'Удалить' if ff.object.deletable_by?(current_user)
								td = ff.object.document_type.name
								td = link_to icon(:download, :medium), "/docs/get/#{ff.object.id}", title: 'Открыть', target: '_blank'
				p = f.link_to_add icon(:plus, :medium), :documents, data: { target: '#documents' }, title: 'Добавить файл' unless @order.state == 'shipped'

	

app/views/orders/_nomenclature_list_for_distributor.html.slim
.row
  .large-9.large-centered.columns
    - distrs = Distributor.all
    dl.sub-nav
      dt Дистрибьютор:
      - distrs.each do |d|
        dd = link_to "#{d.name}", "set_distr/#{d.id}", remote: true, data: {distributor_id: d.id}
    #n-list
      h2 Выбор номенклатуры



= link_to icon(:"x-circle", :medium), '#', class: 'close-reveal-modal'

app/views/orders/_nomenclature_search.html.slim
.row
  .large-9.large-centered.columns
    #n-search
      h2 Выбор номенклатуры
      - unless @nomenclatures.nil?
        = paginate @nomenclatures, remote: true
        #nomenclature-table
          = render 'orders/nomenclature_table'


= link_to icon(:"x-circle", :medium), '#', class: 'close-reveal-modal'

app/views/orders/_nomenclature_table.html.slim
table
  - unless @nomenclatures.empty?
    - @nomenclatures.each do |nom|
      tr
        td = link_to icon(:plus, :medium), '#', class: 'select-nomenclature', data: {nomenclature_id: nom.id, price_id: nom.prices.first.id, no_turbolink: true}
        td = nom.partner_number
        td = nom.name
        td.currency.text-right = number_to_currency(nom.prices.first.price)
  - else
    p Для этого дистрибьютора не заданы цены номенклатуры
    = link_to 'Перейти в справочник номенклатуры', nomenclatures_path, class: 'button secondary'

app/views/orders/_order_items.html.slim
table
  th Партнерский номер
  th Описание
  th Цена
  th Кол-во
  th Сумма
  th НДС
  - @order_items.each do |oi|
    tr
      td = oi.partner_number
      td = oi.nomenclature.name
      td.currency = number_to_currency(oi.price)
      td.text-center = oi.quantity
      td.currency = number_to_currency(oi.summa)
      td.currency = number_to_currency(oi.nds)
  tr.total-row
    td(colspan="4") Всего:
    td.currency = number_to_currency(@order.total_summa)
    td.currency = number_to_currency(@order.total_nds)

app/views/orders/_orders_table.html.slim
= paginate @orders, options: {data: {push: 'partial', target: '#orders'}}
table
  tr
    - if @user_roles.include?('logist')
      th Дистрибьютор
    th Номер
    th Дата
    th Статус
    th Примечание
    th Док&#8209;ты
    th Сумма
    th НДС <span class="small">(в т.ч.)</span>
    th
    th
    th
  - @orders.each do |order|
    tr
      - if @user_roles.include?('logist')
        td = order.distributor.name unless order.distributor.blank?
      td.text-center = order.id
      td = order.created_at.to_time.to_s(:ru_date)
      td(class="#{order.state_name} text-center") = order.human_state_name
      td = order.memo
      td.text-center = icon(:check, :medium) if order.docs
      td.currency = number_to_currency(order.total_summa)
      td.currency = number_to_currency(order.total_nds)
      td = link_to icon(:eye, :medium), order, title: 'Открыть', data: {push: true, target: '#main'}
      td = link_to icon(:pencil, :medium), edit_order_path(order) + '#', title: 'Изменить'
      td = link_to icon(:trash, :medium), order, data: {:confirm => 'Вы уверены?'}, :method => :delete, title: 'Удалить' \
          if order.deletable_by?(current_user)
= paginate @orders, options: {data: {push: 'partial', target: '#orders'}}

app/views/orders/_show.html.slim
== render partial: 'documents/documents_table'

app/views/orders/edit.html.slim
- title = "Изменение заказа №#{@order.id} от #{@order.created_at.to_time.to_s(:ru_date)}"
.row
  .large-12.columns
    h3 = title

    - if current_user.has_role? :distributor
      == render 'form'
    - else
      == render 'form_logist'

- set_title(title)

app/views/orders/edit.js.erb
$('#nomenclature').html('<%= escape_javascript(render 'nomenclature_search') %>');

app/views/orders/index.html.slim
- title = 'Список заказов'
- set_title(title)
.row
  .large-3.columns
    h3 = title
  .large-2.columns.end
    = link_to "Добавить новый", new_order_path + '#', class: 'button secondary tiny'
.row
  .large-9.columns
    #orders
      == render partial: 'orders/orders_table'
  .large-3.columns
    == render 'filter'

app/views/orders/new.html.slim
- title = "Новый заказ"
.row
  .large-12.columns
    h2 = title
    - if current_user.has_role? :distributor
      == render 'form'
    - else
      == render 'form_logist'

    = link_to 'Назад', orders_path, class: 'button secondary small'

- set_title(title)

app/views/orders/show.html.slim
- title = "Заказ №#{@order.id} от #{@order.created_at.to_time.to_s(:ru_date)}"
h3 = title
.row
  .small-8.columns
    == render 'order_items'
    .row
      .large-4.large-centered.columns
        ul.button-group
          li
            = link_to 'Изменить', edit_order_path(@order) +'#', class: 'button secondary small'
          li
            = link_to 'Назад', session[:previous_path], class: 'button secondary small', data: {push: true, target: '#main'}
    hr


  .small-4.columns
    panel
      dl
        dt Статус заказа:
        dd == "<span class=\"#{@order.state_name} button tiny\"> #{@order.human_state_name} </span>"
        dt Комментарий:
        dd = @order.memo
        - if @order.docs
          dt = icon(:'page-doc', :large) + " Документы получены"

.row
  .large-3.columns
    h4 Документы
  .large-9.columns
    = link_to 'Добавить', new_order_document_path(@order), class: 'button tiny secondary'
.row
  .large-12.columns
    #documents
      == render partial: 'documents/documents_table'

- set_title(title)