config/routes.rb
Docs::Application.routes.draw do
  mount RailsAdmin::Engine => '/app_admin', :as => 'rails_admin'
  devise_for :users
  comfy_route :cms_admin, path: '/site_admin'

  authenticated do
    root to: 'home#loggedin', as: :autenticated_root
  end

  root to: 'comfy/cms/content#show'


  resources :revises do
    member do
      get :fix
      get :unfix
      get :download
    end
  end

  get 'invoices', to: 'documents#invoices'
  get 'delivers', to: 'documents#delivers'

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end

  resources :nomenclatures do
    get :archived, on: :collection
  end
  resources :distributors, except: :show
  resources :documents, only: [:show, :edit, :update, :destroy] do
    member do
      get :download
    end
  end
  resources :orders do
    resources :documents, only: [:new, :create]
    member do
      get :accept
      get :pay
      get :ship
      get :unaccept
      get :unpay
      get :unship
    end
  end

  resources :messages do
    member do
      get :reply
      get :download
      get :sdestroy
    end
  end
  get 'outbox', to: 'messages#outbox'
  get '/docs/get/:id' => 'orders#download'

  get '/prices/:id' => 'prices#show', defaults: { format: 'json' }

  # Make sure this routeset is defined last
  comfy_route :cms, path: '/', sitemap: false


end

app/models/document.rb
class Document < ActiveRecord::Base
  include Authority::Abilities
  self.authorizer_name = 'DocumentAuthorizer'

  paginates_per 10

  belongs_to :order, touch: true
  belongs_to :document_type
  belongs_to :user
  has_one :distributor, through: :order

  mount_uploader :file, DocumentUploader
  validates :file, :document_type, :user, presence: true

  scope :invoices, -> { where document_type_id: DocumentType.where(tab: DocumentType.tabs[:invoices]) }
  scope :delivers, -> { where document_type_id: DocumentType.where(tab: DocumentType.tabs[:delivers]) }
  scope :current_distr, -> { joins(:distributor).where('distributors.id =?', Distributor.current) }

  def read_uploader(column)
    self[column]
  end

  def write_uploader(column, identifier)
    self[column] = identifier
  end

  def user
    User.unscoped { super }
  end

  def document_type
    DocumentType.unscoped { super }
  end
end

app/models/document_type.rb
class DocumentType < ActiveRecord::Base
  enum tab: { invoices: 1, delivers: 2 }
  acts_as_paranoid

  validates :name, :tab, presence: true

  scope :for_distributor, -> { where(distr: true) }

  rails_admin do
    list do
      field :name do
        label 'Наименование'
      end
      field :distr do
        label 'Доступно дистрибьюторам'
      end
      field :tab do
        label 'Вкладка'
        pretty_value do
          I18n.t :"documenttype_tab.#{bindings[:object].tab}"
        end
      end
    end

    edit do
      field :name do
        label 'Наименование'
      end
      field :distr do
        label 'Доступно для дистрибьюторов'
      end
      field :tab, :enum do
        enum do
          [['Счета, платежки', :invoices], ['Накладные, счета-фактуры', :delivers]]
        end
        label 'Вкладка'
      end
    end
  end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  include EmailNotify
  before_action :authenticate_user!
  before_action :set_order, only: [:new, :create]
  before_action :set_document, only: [:edit, :show, :update, :destroy, :download]
  before_action :check_mime, only: [:show]
  def invoices
    session[:previous_path] = invoices_path
    @search = Document.invoices.includes(:order).order('created_at desc').search(params[:q])
    select_documents
  end

  def delivers
    session[:previous_path] = delivers_path
    @search = Document.delivers.includes(:order).order('created_at desc').search(params[:q])
    select_documents
  end

  def new
    @document = @order.documents.new
  end

  def create
    @document = @order.documents.new(document_params)
    respond_to do |format|
      if @document.save
        format.html { redirect_to @order, notice: 'Документ добавлен' }
        format.json { render action: 'show', status: :created, location: @document }
        notice('document_added', order: @order, document: @document)
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize_action_for(@document)
    @back_url = back_to(@document)
  end

  def update
    authorize_action_for(@document)
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to back_to(@document), notice: 'Изменения успешно внесены.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize_action_for(@document)
    @document.destroy
    respond_to do |format|
      format.html { redirect_to back_to(@document) }
      format.json { head :no_content }
    end
  end

  def download
    authorize_action_for(@document)
    path = URI.decode(@document.file.url)
    send_file path, x_sendfile: false, filename: setup_filename(@document.file.file.filename)
  end
  authority_actions download: 'read'

  def show
    authorize_action_for(@document)
    extension = @document.file.file.extension.downcase
    disposition = 'attachment'
    mime = MIME::Types.type_for(@file).first.content_type
    disposition = 'inline' if %w(jpg png gif bmp pdf txt).include?(extension)
    send_file @file, type: mime, disposition: disposition, x_sendfile: false, filename: setup_filename(@document.file.file.filename)
  end

  private

  def check_mime
    @file = URI.decode(@document.file.url)
    if MIME::Types.type_for(@file).first.nil?
      redirect_to download_document_path(@document)
    end
  end

  def select_documents
    if current_user.has_role? :distributor
      @documents = @search.result.current_distr.page(params[:doc_page])
    else
      @documents = @search.result.page(params[:doc_page])
    end
    render partial: 'documents/documents_table' if request.wiselinks_partial?
  end

  def set_order
    @order = Order.find(params[:order_id])
  end

  def set_document
    @document = Document.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:file, :order_id, :document_type_id, :user_id, :doc_date, :doc_no, :memo, :summa)
  end

  def back_to(doc)
    "#{doc.document_type.tab}".to_sym
  end
end

app/views/documents/_documents_table.html.slim
= paginate @documents, param_name: 'doc_page', options: {data: { push: 'partial', target: '#documents' } }
- logist = current_user.has_role? :logist
table
  tr
    th Дата
    th Номер
    th Сумма
    th Тип
    - if logist
      th Дисти
    th Комментарий
    th Заказ
    th(colspan="4") Действия
  - @documents.each do |doc|
    tr
      td = doc.doc_date.strftime('%d.%m.%Y') unless doc.doc_date.blank?
      td.text-center = doc.doc_no
      td.currency = number_to_currency(doc.summa)
      td = doc.document_type.name
      - if logist
        td = doc.distributor.name
      td = doc.memo
      td.text-center = link_to "#{doc.order.id}", order_path(doc.order), data: { push: 'true', target: '#main'}
      td = link_to icon(:pencil, :medium), edit_document_path(doc), data: { push: 'true', target: '#main'} if doc.updatable_by?(current_user)
      td = link_to icon(:eye, :medium), document_path(doc), title: 'Посмотреть', target: '_blank'
      td = link_to icon(:download, :medium), download_document_path(doc), title: 'Скачать', target: '_blank'
      td = link_to icon(:trash, :medium), doc, data: {:confirm => 'Вы уверены?'}, method: :delete, title: 'Удалить' if doc.deletable_by?(current_user)

- if @documents.blank? && params[:q]
  - if params[:q][:order_id_eq]
    .row
      .large-6.large-centered.columns
        - order_id = params[:q][:order_id_eq]
        - if @order = Order.find_by_id(order_id)
          = link_to 'Добавить документ', new_order_document_path(@order), class: 'button secondary tiny'
        - else
          p = "Заказ №#{order_id} не существует"


= paginate @documents, param_name: 'doc_page', options: {data: { push: 'partial', target: '#documents' } }

app/views/documents/_filter.html.slim
- if tab == 'invoices'
  - url = invoices_path
  - doctypes = DocumentType.where(tab: DocumentType.tabs[:invoices])
- else
  - url = delivers_path
  - doctypes = DocumentType.where(tab: DocumentType.tabs[:delivers])
= search_form_for @search, url: url, defaults: {required: false}, data: { push: 'partial', target: '#documents'} do |f|
  fieldset
    legend Фильтр
    .row
      .large-6.columns
        = f.input :doc_no_eq, label: false, input_html: { placeholder: 'Номер док-та', autocomplete: "off" }
      .large-6.columns
        .row.collapse
          .large-10.columns
            = f.input :doc_date_eq, as: :datepicker, label: false, input_html: { placeholder: 'Дата док-та' }
          .large-2.columns
            span.postfix#clear-datepicker(data-no-turbolinks="true") X
    - if @user_roles.include?('logist')
      .row
        .large-12.columns
          = f.input :distributor_id_eq, as: :select, collection: Distributor.all, label: 'Дистрибьютор'
    .row
      .large-6.columns
        = f.input :order_id_eq, label: 'Номер заказа', input_html: { autocomplete: "off" }
      .large-6.columns
        = f.input :document_type_id_eq, as: :select, collection: doctypes, label: 'Тип документа'


    = f.submit "Найти", class: 'button secondary tiny'
    = link_to 'Очистить', session[:previous_path], class: 'button secondary tiny', data: {push: true, target: '#main'}

app/views/documents/_form.html.slim
- user_logist = current_user.has_role? :logist
= simple_form_for(@document) do |f|
  = f.error_notification

  == render partial: 'form_fields', locals: { f: f }

app/views/documents/_form_fields.html.slim
- user_logist = current_user.has_role? :logist
.form-inputs
    .row
      .large-3.columns
        = f.input :doc_no, label: false, input_html: { placeholder: 'Номер' }
        .row.collapse
          .large-10.columns
            = f.input :doc_date, as: :datepicker, label: false, \
              input_html: { placeholder: 'Дата', value: @document.doc_date.blank? ? '' : @document.doc_date.strftime('%d.%m.%Y') }
          .large-2.columns
            span.postfix#clear-datepicker(data-no-turbolinks="true") X
        = f.input :summa, as: :currency, label: false, input_html: { placeholder: 'Сумма' }
        = f.association :document_type, label: 'Тип документа', collection: user_logist ? DocumentType.all : DocumentType.for_distributor
      .large-9.columns
        = f.input :memo, label: 'Комментарий:', input_html: {rows: 4}
        = f.input :file, as: :file, label: false

.row
  .large-6.large-centered.columns
    .form-actions
      = f.button :submit, 'Сохранить'

app/views/documents/_form_new.html.slim
= simple_form_for([@order, @document]) do |f|
  = f.error_notification
  = f.association :user, as: :hidden, input_html:  {value: current_user.id}

  == render partial: 'form_fields', locals: { f: f }

app/views/documents/delivers.html.slim
- title = 'Накладные и счета-фактуры'
- set_title(title)
.row
  .large-5.columns
    h3 = title
.row
  .large-9.columns
    #documents
      == render partial: 'documents_table'
  .large-3.columns
    == render partial: 'filter', locals: { tab: 'delivers' }

app/views/documents/edit.html.slim
- title = 'Редактирование документа'
- set_title(title)
h3 = title
.row
  .large-8.large-centered.columns
    == render 'form'

.row
  .large-8.large-centered.columns
    ul.button-group
      li = link_to 'Показать', @document, class: 'button secondary', data: { push: true, target: '#main'}
      li = link_to 'Назад', @back_url, class: 'button secondary', data: { push: true, target: '#main'}

app/views/documents/invoices.html.slim
- title = 'Счета и платёжные поручения'
- set_title(title)
.row
  .large-5.columns
    h3 = title
.row
  .large-9.columns
    #documents
      == render partial: 'documents_table'
  .large-3.columns
    == render partial: 'filter', locals: { tab: 'invoices' }

app/views/documents/new.html.slim
- title = "Новый документ к заказу №#{@order.id}"
- set_title(title)

h3 = title
.row
  .large-8.large-centered.columns
    == render 'form_new'

.row
  .large-8.large-centered.columns
    ul.button-group
      li = link_to 'Назад', :back, class: 'button secondary'