config/routes.rb
Docs::Application.routes.draw do
  mount RailsAdmin::Engine => '/app_admin', :as => 'rails_admin'
  devise_for :users
  comfy_route :cms_admin, path: '/site_admin'

  authenticated do
    root to: 'home#loggedin', as: :autenticated_root
  end

  root to: 'comfy/cms/content#show'


  resources :revises do
    member do
      get :fix
      get :unfix
      get :download
    end
  end

  get 'invoices', to: 'documents#invoices'
  get 'delivers', to: 'documents#delivers'

  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    delete '/logout' => 'devise/sessions#destroy'
  end

  resources :nomenclatures do
    get :archived, on: :collection
  end
  resources :distributors, except: :show
  resources :documents, only: [:show, :edit, :update, :destroy] do
    member do
      get :download
    end
  end
  resources :orders do
    resources :documents, only: [:new, :create]
    member do
      get :accept
      get :pay
      get :ship
      get :unaccept
      get :unpay
      get :unship
    end
  end

  resources :messages do
    member do
      get :reply
      get :download
      get :sdestroy
    end
  end
  get 'outbox', to: 'messages#outbox'
  get '/docs/get/:id' => 'orders#download'

  get '/prices/:id' => 'prices#show', defaults: { format: 'json' }

  # Make sure this routeset is defined last
  comfy_route :cms, path: '/', sitemap: false


end

app/views/layouts/_admin_panel.html.slim
.panel
  h5 Администратор
  ul.button-group
    li = link_to 'Управление', rails_admin_path, class: 'button secondary'

app/views/layouts/_distr_panel.html.slim
.panel
  h5 Дистрибьютор
  ul.button-group
    li = link_to "Заказы", orders_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    li = link_to 'Счета и платёжки', invoices_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    li = link_to 'Накладные и сч-ф', delivers_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    li = link_to 'Акты сверок', revises_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    - cl = 'fi-mail icon-mail'
    li = link_to "<i class='#{cl}' id='mailbox'></i>".html_safe, messages_path, class: 'button secondary'

app/views/layouts/_header.html.slim
.contain-to-grid
  nav.top-bar[data-topbar="" data-options="is_hover: false"]
    ul.title-area
      li.name
        h1 
          = link_to 'Docs', root_path
      li.toggle-topbar.menu-icon
        a href="#"
          span Меню
    section.top-bar-section
      ul.right
        li = link_to 'Главная', root_path
        li = link_to 'О нас', '#'
        li = link_to 'Продукты', '#'
        li = link_to 'Партнёрам', '#'
        li = link_to 'Контакты', '#'

app/views/layouts/_logist_panel.html.slim
.panel
  h5 Логист
  ul.button-group
    li = link_to 'Заказы', orders_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    li = link_to 'Счета и платёжки', invoices_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    li = link_to 'Накладные и сч-ф', delivers_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    li = link_to 'Акты сверок', revises_path, class: 'button secondary', data: {push: 'true', target: '#main'}
    li
      = link_to 'Справочники', '#', data: {dropdown: 'drop-catalog'}, class: 'button secondary dropdown'
      ul#drop-catalog.f-dropdown(data-dropdown-content)
        li = link_to 'Номенклатура', nomenclatures_path
        li = link_to 'Дистрибьюторы', distributors_path
    - cl = 'fi-mail icon-mail'
    li = link_to "<i class='#{cl}' id='mailbox'></i>".html_safe, messages_path, class: 'button secondary'

app/views/layouts/_messages.html.slim
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div.alert-box class="#{name.to_s == 'notice' ? 'success' : 'alert'}" data-alert=""
      = content_tag :div, msg, id: "flash_#{name}", class: 'text-center'
      a.close href="#" &times;

app/views/layouts/_navigation.html.slim
nav.top-bar[data-topbar="" data-options="is_hover: false" role="navigation"]
  ul.title-area
    li.name
      h1 = link_to 'Docs', root_path
    li.toggle-topbar.menu-icon
      = link_to content_tag(:span, 'Меню'), '#'
  section.top-bar-section
    - if current_user
      ul.left
        = render 'layouts/navigation_links'
    ul.right
      li.divider
      - if current_user
        li
          = link_to current_user.email, "#", data: {dropdown: "drop1"}
          ul#drop1.f-dropdown(data-dropdown-content="")
            li = link_to 'Выход', Rails.env.development? ? logout_path : logout_url, method: :delete
      - else
        li
          = link_to 'Войти', Rails.env.development? ? login_path : login_url(protocol: 'https')

app/views/layouts/_navigation_links.html.slim
// add navigation links to this file

app/views/layouts/application.html.slim
doctype 5
|<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="ru"> <![endif]-->
|<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="ru"> <![endif]-->
|<!--[if IE 8]><html class="no-js lt-ie9" lang="ru"> <![endif]-->
|<!--[if gt IE 8)><!-->
html.no-js(lang="ru")
  |<!--<![endif]-->
  head
    meta charset="utf-8"
    /[if IE]
      meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title
      - if content_for(:title)
        = yield :title
      - elsif @cms_page
        = "#{@cms_site.label} | #{@cms_page.label}"
      - else
        |Application
    = stylesheet_link_tag 'application', media: 'all'
    = stylesheet_link_tag comfy_cms_render_css_path(@cms_site.id, @cms_layout.identifier) if @cms_site
	= javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag comfy_cms_render_js_path(@cms_site.id, @cms_layout.identifier) if @cms_site
  body
    .row.full-width
      .columns
        header.border-bottom
          = render 'layouts/navigation'
          = render 'layouts/messages'
    main(role='main')
      = yield

app/views/layouts/loggedin.html.slim
doctype 5
|<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="ru"> <![endif]-->
|<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8" lang="ru"> <![endif]-->
|<!--[if IE 8]><html class="no-js lt-ie9" lang="ru"> <![endif]-->
|<!--[if gt IE 8)><!-->
html.no-js(lang="ru")
  |<!--<![endif]-->
  head
    meta charset="utf-8"
    /[if IE]
      meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title = content_for?(:title) ? yield(:title) : "Docs"
    = stylesheet_link_tag "application", media: "all"
    = stylesheet_link_tag "foundation-icons", media: "all"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body

    .row.full-width
      header.border-bottom
        = render 'layouts/navigation'
      .small-3.small-centered.columns
      .loading-indicator(style="display: none;")
      br
      .row
        .large-12.columns
          - if @user_roles.include?('logist')
            .large-9.columns
              = render 'layouts/logist_panel'
          - if @user_roles.include?('distributor')
            .large-9.columns
              = render 'layouts/distr_panel'
          - if @user_roles.include?('admin')
            .large-3.columns
              = render 'layouts/admin_panel'
        hr
      .row
        .large-12.columns#main
          = render 'layouts/messages'
          = yield
    //footer
    footer
      .row
        .large-12.columns
          hr
          